# This file has all of the thruster layout information needed by the sub
# This is used when simulating or running actual thrusters.
# CONFIDENT_MODE means that the thrusters on this port will never go offline (command packets
#   will always be sent even if no responses are received)

thruster_ports:
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if00-port0
    thruster_names: [FLH, FLV]
    CONFIDENT_MODE: False
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if01-port0
    thruster_names: [FRH, FRV]
    CONFIDENT_MODE: False
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if02-port0
    thruster_names: [BLH, BLV]
    CONFIDENT_MODE: False
  - port: /dev/serial/by-id/usb-MIL_Data_Merge_Board_Ports_1_to_4_DMBP14-if03-port0
    thruster_names: [BRH, BRV]
    CONFIDENT_MODE: False

# node_id's should be globally unique among all thrusters
# position and orientation vectors should be specified in body frame
# calib contains the 4th to 1st order coefficients for a polynomial
#     mapping from thrust in Newtons to effort (e = t[0]x^4 + t[1]x^3 + t[2]x^2 + t[3]x)
thrusters:
  FLH: {
    node_id:  3,
    position:  [0.2678, 0.2795, 0.0],
    direction: [0.866, -0.5, 0.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }
  FLV: {
    node_id:  1,
    position:  [0.1583, 0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }
  FRH: {
    node_id:  2,
    position:  [0.2678, -0.2795, 0.0],
    direction: [0.866, 0.5, 0.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }
  FRV: {
    node_id:  0,
    position:  [0.1583, -0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }
  BLH: {
    node_id:  4,
    position:  [-0.2678, 0.2795, 0.0],
    direction: [-0.866, -0.5, 0.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }
  BLV: {
    node_id:  5,
    position:  [-0.1583, 0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }
  BRH: {
    node_id:  6,
    position:  [-0.2678, -0.2795, 0.0],
    direction: [-0.866, 0.5, 0.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }
  BRV: {
    node_id:  7,
    position:  [-0.1583, -0.169, 0.0142],
    direction: [0.0, 0.0, 1.0],
    thrust_bounds:    [-83.77, 101.64],
    calib:  {
        forward:  [-1.85158e-08, 4.17219e-06, -0.000332, 0.019416, 0.051559],
        backward: [2.85455e-08, 5.8469e-06, 0.000422, 0.022321, -0.060047]
    }
  }

